package dambi.accessingmongoumeak.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import dambi.accessingmongoumeak.model.Diskoak;
import dambi.accessingmongoumeak.model.DiskoakRepository;

@RestController // This means that this class is a Controller baina @Controller bakarrik jarrita, PUT eta DELETEak ez dabiz
@RequestMapping(path = "/diskak") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called umeaRepository
				// Which is auto-generated by Spring, we will use it to handle the data
	private DiskoakRepository diskoakRepository;

	@GetMapping(path = "/diskoguztiak")
	public @ResponseBody Iterable<Diskoak> getAllDiskoak() {
		// This returns a JSON or XML with the users
		return diskoakRepository.findAll();
	}

	@GetMapping(path = "/diskokantitatea")
	public @ResponseBody int getAllDiskoKantitatea() {
		// This returns a JSON or XML with the users
		int diskoKantitatea = 0;
		for (int i = 0; i <= diskoakRepository.findAll().size(); i++) {
			diskoKantitatea++;
		}
		
		return diskoKantitatea -1;
	}

}
