package dambi.accessingmongodiskografia.controller;

import java.util.List;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import dambi.accessingmongodiskografia.model.Diskoa;
import dambi.accessingmongodiskografia.model.DiskografiaRepository;

@RestController // This means that this class is a Controller baina @Controller bakarrik jarrita, PUT eta DELETEak ez dabiz
@RequestMapping(path = "/diskoak") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called diskografiaRepository
				// Which is auto-generated by Spring, we will use it to handle the data
	private DiskografiaRepository diskografiaRepository;

	
	
}